### PR TITLE
feat: add outputs to get the preview-url and preview-name

### PR DESCRIPTION
**Pull request by semoal**
## Description

Basically I want to get the preview-url generated by netlify to run some e2e tests and Lighthouse suite to that URL.

Vercel deployment action already does this.

### CODE REVIEW

**Comment by T-Philipp** [comment]
@South-Paw this PR is opened since July....

**Comment by semoal** [comment]
> @South-Paw this PR is opened since July....

I've ended up using mine which is the fork of South Paw.  

You can see here https://github.com/verdaccio/verdaccio/blob/master/.github/workflows/website.yml#L92

**Comment by South-Paw** [comment]
@T-Philipp Yeah, open source software is like that, sometimes people miss things, sometimes they are busy, sometimes they've chosen to not to use their spare time on free projects and sometimes its just a combination of everything. I have PRs and issues that were raised years ago and never even got a maintainers response - that's just how free software is sometimes.

Now that being said, @semoal I apologize that it hasn't been looked at, I know how frustrating it is but its just one of those things that got lost in my notifications and I haven't been spending my spare time keeping track of.

I'll get it in now.

However, as mentioned in #21 `deploy` has been removed in a newer version of Netlify's js client and I have been planning to write up a migration path for people who use this action so they can just change over to using the Netlify CLI + a deployments action to replace this action.

**Comment by T-Philipp** [comment]
perfect.
Thanks a lot both of you 😁👍

**Comment by South-Paw** [comment]
@T-Philipp @semoal [v1.2.1](https://github.com/marketplace/actions/netlify-deploy-action) is on marketplace now

**Pull request merged**
